## Noor Alawlaqi - S21107270

# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [93]:
# Write your answer here
import numpy as np
#Q1 answer:

zeros = np.zeros(10)
print(zeros)

#Q2 answer:
vowels = np.array(['a', 'e', 'i', 'o' , 'u'])
print(vowels)

#Q3 answer:
ones = np.ones((2,5), dtype=np.int64)
print(ones)

#Q4 answer:
myarray1 = [
    [2.7, 0, -2], 
    [3.4, 10.6, 0], 
    [-19, 99.9, 13]
]
print(myarray1)

#Q5 answer:
myarray2 = np.arange(4,15*4+4,4, dtype=np.float64).reshape(3,5)
print(myarray2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
['a' 'e' 'i' 'o' 'u']
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]]
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [96]:
#Q1 answer:
# for the zeros array and its thhe same for the rest so i could do it 
#in a for loop instead
# zeros.ndim
# zeros.shape
# zeros.size
# zeros.dtype
# zeros.itemsize
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
arrays = [("zeros", zeros), ("vowels", vowels), ("ones", ones),("myarray1", myarray1), ("myarray2", myarray2)]

for name, arr in arrays:
    print(f"\n{name}:")
    print(f"Dimensions: {arr.ndim}")
    print(f"Shape: {arr.shape}")
    print(f"Size: {arr.size}")
    print(f"Data Type: {arr.dtype}")
    print(f"Item Size: {arr.itemsize} bytes")
    
#Q2 answer:
ones2 = ones.reshape(1,10)
print(ones2)

#Q3 answer:
print(vowels[1:3])

#Q4 answer:
print(myarray1[1:])

#Q5 answer:
print(myarray1[:, 0:2])

#Q6 answer:
print(myarray1[1:, 0])

#Q7 answer:
print(vowels[::-1])


zeros:
Dimensions: 1
Shape: (10,)
Size: 10
Data Type: float64
Item Size: 8 bytes

vowels:
Dimensions: 1
Shape: (5,)
Size: 5
Data Type: <U1
Item Size: 4 bytes

ones:
Dimensions: 2
Shape: (2, 5)
Size: 10
Data Type: int64
Item Size: 8 bytes

myarray1:
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: float64
Item Size: 8 bytes

myarray2:
Dimensions: 2
Shape: (3, 5)
Size: 15
Data Type: float64
Item Size: 8 bytes
[[1 1 1 1 1 1 1 1 1 1]]
['e' 'i']
[[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
[[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]
[  3.4 -19. ]
['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [129]:
#Q1 answer:
divided_ones = ones / 3
print(divided_ones) 

#we need to reshape the second array
myarray2_adjusted = myarray2[:, :3]

#Q2 answer:
added_arrays = myarray1 + myarray2_adjusted
print(added_arrays)

#Q3 answer:
subtracted_arrays = myarray2_adjusted - myarray1
print(subtracted_arrays)

#Q4 answer:
multiplied_arrays = myarray1 * myarray2_adjusted
print(multiplied_arrays)

#Q5 answer:
myarray3 = np.dot(myarray1, myarray2_adjusted)
print(myarray3)

#Q6 answer:
divided_arrays = myarray1 / myarray2_adjusted
print(divided_arrays)

#Q7 answer:
cubed_divided = (myarray1 ** 3) / 2
print(cubed_divided)

#Q8 answer:
sqrt_divided = np.round(np.sqrt(myarray2_adjusted) / 2, 2)
print(sqrt_divided)

[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]
[[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]
[[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]
[[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]
[[ -77.2  -74.4  -71.6]
 [ 268.   324.   380. ]
 [2893.6 3269.2 3644.8]]
[[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]
[[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]
[[1.   1.41 1.73]
 [2.45 2.65 2.83]
 [3.32 3.46 3.61]]


Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [102]:
# Write your answer here
#Q1:
transpose_ones = ones.T
print(transpose_ones)

transpose_myarray2 = myarray2.T
print(transpose_myarray2)


#Q2
sorted_vowels = np.sort(vowels)[::-1]
print(sorted_vowels)


#Q3
sorted_myarray1 = np.sort(myarray1, axis=0)
print(sorted_myarray1)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
['u' 'o' 'i' 'e' 'a']
[[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [105]:
# Write your answer here
myarray4 = np.arange(-1, -1 + (14 * 3 * 0.25), 0.25).reshape(14, 3)
print(myarray4)


split_arrays = np.array_split(myarray4, 3, axis=0)
print(split_arrays)

[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]
[array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ]]), array([[2.75, 3.  , 3.25],
       [3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75],
       [5.  , 5.25, 5.5 ],
       [5.75, 6.  , 6.25]]), array([[6.5 , 6.75, 7.  ],
       [7.25, 7.5 , 7.75],
       [8.  , 8.25, 8.5 ],
       [8.75, 9.  , 9.25]])]


Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [108]:
# Write your ansewr here

total_sum = np.sum(myarray4)
print(total_sum)

row_sum = np.sum(myarray4, axis=1)
print(row_sum)

column_sum = np.sum(myarray4, axis=0)
print(column_sum)

max_value = np.max(myarray4)
print(max_value)

row_min = np.min(myarray4, axis=1)
print(row_min)

row_mean = np.mean(myarray4, axis=1)
print(row_mean)

column_std = np.std(myarray4, axis=0)
print(column_std)

173.25
[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
[54.25 57.75 61.25]
9.25
[-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]
[-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
[3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [121]:
# Write your answer here
import pandas as pd
import numpy as np
capitals = pd.read_csv('country-capital-lat-long-population.csv')
capitals.head()

capitals_location = capitals.loc[:,['Latitude','Longitude']].to_numpy()
KSA_locations = capitals.loc[capitals.Country == 'Saudi Arabia',['Latitude','Longitude']].to_numpy()

distance_from_riyadh = np.sqrt(np.sum((KSA_locations - capitals_location)**2,axis=1))
distance_from_riyadh[distance_from_riyadh ==0]=9999

closest = np.argmin(distance_from_riyadh)

capitals.iloc[closest,:]

Country                     Bahrain
Capital City    Al-Manamah (Manama)
Latitude                    26.2154
Longitude                   50.5832
Population                   564631
Capital Type                Capital
Name: 15, dtype: object

#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [127]:
closest_capitals = []

capitals_location = capitals.loc[:,['Latitude','Longitude']].to_numpy()
US_locations = capitals.loc[capitals.Country == 'United States of America',['Latitude','Longitude']].to_numpy()


for i in range(10):
    distance_from_washington = np.sqrt(np.sum((US_locations - capitals_location)**2,axis=1))
    distance_from_washington[distance_from_washington ==0]=9999

    closest = np.argmin(distance_from_washington)

    closest_capitals.append(capitals.iloc[closest, :])

    capitals_location[closest] = [9999, 9999]  # This will ensure it's not picked again
closest_capitals_df = pd.DataFrame(closest_capitals)

print(closest_capitals_df)

                       Country        Capital City  Latitude  Longitude  \
36                      Canada     Ottawa-Gatineau   45.4166   -75.6980   
14                     Bahamas              Nassau   25.0582   -77.3431   
22                     Bermuda            Hamilton   32.2915   -64.7780   
55                        Cuba  La Habana (Havana)   23.1195   -82.3785   
215   Turks and Caicos Islands       Cockburn Town   21.4612   -71.1419   
38              Cayman Islands         George Town   19.2866   -81.3744   
94                       Haiti      Port-au-Prince   18.5392   -72.3350   
107                    Jamaica            Kingston   17.9970   -76.7936   
64          Dominican Republic       Santo Domingo   18.4896   -69.9018   
177  Saint Pierre and Miquelon        Saint-Pierre   46.7738   -56.1815   

     Population Capital Type  
36      1363159      Capital  
14       279668      Capital  
22        10073      Capital  
55      2136468      Capital  
215        5447    